---
# Source: helm for kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lala
  labels:
    app: lala
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lala
  template:
    metadata:
      labels:
        app: lala
    spec:
      containers:
        - name: lala
          image: docker.io/phengbunath/lala:1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
